"""{{ source_name }} data source for ÆON.

Generated by ModuleGenerator on {{ timestamp }}.
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


class {{ class_name }}:
    """Data source for {{ source_name }} using {{ protocol }}.

    Schema hints: {{ schema_hints }}
    """

    def __init__(self, endpoint: str = "") -> None:
        self.endpoint = endpoint
        self._connected = False

    async def connect(self) -> None:
        """Open {{ protocol }} connection."""
        logger.info("Connecting to %s at %s", "{{ source_name }}", self.endpoint)
        self._connected = True

    async def ingest(self) -> list[dict[str, Any]]:
        """Ingest a batch of records."""
        # TODO: implement ingestion logic
        return []

    async def disconnect(self) -> None:
        """Close connection."""
        self._connected = False
        logger.info("Disconnected from %s", "{{ source_name }}")
