"""{{ app_name }} React frontend for ÆON.

Generated by ModuleGenerator on {{ timestamp }}.
"""

// This is a placeholder JSX template for {{ app_name }}
// Pages: {{ pages }}
// API base URL: {{ api_base_url }}

import React, { useState, useEffect } from "react";

export default function {{ class_name }}() {
  const [data, setData] = useState(null);
  const apiUrl = "{{ api_base_url }}";

  useEffect(() => {
    fetch(`${apiUrl}/health`)
      .then((r) => r.json())
      .then((d) => setData(d))
      .catch((e) => console.error(e));
  }, []);

  return (
    <div>
      <h1>{{ app_name }}</h1>
      {/* TODO: implement pages and routing for {{ pages }} */}
      <pre>{JSON.stringify(data, null, 2)}</pre>
    </div>
  );
}
