"""Data classes for the Cortex reasoning engine."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum, auto
from typing import Any


class DecisionType(Enum):
    """Classification of a Cortex decision."""

    TRADE = auto()
    PRODUCT_LAUNCH = auto()
    DATA_SUBSCRIPTION = auto()
    COMPUTE_UPGRADE = auto()
    HIBERNATE = auto()
    LIQUIDATE = auto()
    NO_OP = auto()


class RecoveryStrategy(Enum):
    """Available autonomous recovery strategies."""

    RETRY_WITH_BACKOFF = auto()
    SWITCH_DATA_SOURCE = auto()
    ENTER_HIBERNATION = auto()
    LIQUIDATE_POSITIONS = auto()
    DEGRADE_CAPABILITY = auto()
    ABORT_AND_LOG = auto()


@dataclass(frozen=True, slots=True)
class Plan:
    """Strategic plan generated by the StrategicPlanner."""

    goals: list[str]
    target_revenue: float
    risk_tolerance: float
    capability_priorities: list[str]
    tier: int
    horizon: str  # "daily" or "weekly"
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class Decision:
    """Tactical decision produced by the TacticalExecutor."""

    decision_type: DecisionType
    symbol: str | None
    side: str | None
    quantity: float
    price: float | None
    confidence: float
    expected_profit: float
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass(frozen=True, slots=True)
class ReasoningReceipt:
    """Receipt justifying the cost of a reasoning operation."""

    cost: float
    expected_value: float
    go: bool
    confidence: float
    mode: str  # "frugal" or "deep"
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class RecoveryAction:
    """Action prescribed by FailureRecovery."""

    strategy: RecoveryStrategy
    description: str
    retry_count: int
    backoff_seconds: float
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
